# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_auto_20170317_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='User Rating'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Expert Rating'),
        ),
    ]
