# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_auto_20170317_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user_rating',
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_rating', to='details.Book'),
        ),
    ]
