# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_auto_20170320_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='availability',
            field=models.BooleanField(default=False, verbose_name='available for sale or not.'),
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_rating', to='details.Book'),
        ),
    ]
